### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by AnthonyProvenza** [AnthonyProvenza/RubyUI#1]
Here's a list of things I've got to do

- [x] Complete the inverted buttons in all colors
- [ ] Finish the landing page with a nice parallax background
- [ ] Work on the README.md
- [ ] Add the wiki
- [ ] Create a github.io page

**Comment by AnthonyProvenza** [comment]
- [ ] Add outline buttons (combination of the regular ones and the inverted)
